# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - car-price

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://cars1.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e10b61f8bcbd49cd9f6a2a9e0384648b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6e2af42425ed4e10a2be33f5d1585254 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cars1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e10b61f8bcbd49cd9f6a2a9e0384648b }}/cars-price-prediction:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'car-price'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ae9ededf1d524c1182c48dc6b64a7a94 }}
        images: 'cars1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e10b61f8bcbd49cd9f6a2a9e0384648b }}/cars-price-prediction:${{ github.sha }}'